version: '2.4'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    #    environment:
    #      - STORAGE_TYPE=mem
    #      - MYSQL_HOST=mysql
    ports:
      - 9411:9411