apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: currency-conversion
    spec:
      containers:
        - image: 22071996/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: mmv2-currency-conversion-service
          envFrom:
            - configMapRef:
                name: currency-conversion
          readinessProbe:
            httpGet:
              port: 8000
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8000
              path: /actuator/health/liveness
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: currency-conversion
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
  SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
kind: ConfigMap
metadata:
  name: currency-conversion
  namespace: default