apiVersion: v1
data:
  CURRENCY_EXCHANGE_URI: http://currency-exchange
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-13T13:12:44Z"
  name: currency-conversion
  namespace: default
  resourceVersion: "3178043"
  uid: 9495f51a-08ee-4370-942e-e7a46555cc37
